### ISSUE TITLE
Update the terms API 

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/terms-service#30]
- Remove the `noauth` from `GET /terms/:id` and replace the implementation with a logical v5 standard way to do this.
- Remove the `/terms/docusignCallback` endpoint and all related code. The functionality will be moved over to the https://github.com/topcoder-platform/terms-receiver/ project
- Update Swagger

cc @rootelement

**Comment by mtwomey** [comment]
Community-app side issue: https://github.com/topcoder-platform/community-app/issues/4609

**Comment by ThomasKranitsas** [comment]
PR: https://github.com/topcoder-platform/terms-service/pull/31

**Comment by ThomasKranitsas** [comment]
PR: https://github.com/topcoder-platform/terms-service/pull/32

**Comment by lakshmiathreya** [comment]
@mtwomey - pls give access to this repo - for me (lakshmiathreya) and Sathya (SathyaJayabal).

**Comment by rootelement** [comment]
Issue fixed
