### ISSUE TITLE
[Admin App] Support filter TermsOfUse by "title"

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/terms-service#37]
We need this feature to manage Terms in Admin App see https://github.com/topcoder-platform/admin-app/issues/152.

Terms Service has endpoint `GET https://api.topcoder-dev.com/v5/terms` which returns the list of **TermsOfUse**. Currently, it only supports filtering by `legacyId`, see [source code](https://github.com/topcoder-platform/terms-service/blob/dev/src/services/TermsOfUseService.js#L453) and [swagger screenshot](https://monosnap.com/file/lJaSj73cP8bTjyVaXtirhZjoL1T1JI).

We need to support filtering **TermsOfUse** by `title`:
- it should filter records by `title` using substring
- it should filter case-insesetive

So the call like `GET https://api.topcoder-dev.com/v5/terms?title=test` would return records of **TermsOfUse** with title like `TEST`, `Support testing`, `pretesting` and so on, which contain substring `test`.

**Comment by rootelement** [comment]
@maxceem i believe this is complete and can be closed, right?

**Comment by maxceem** [comment]
Yes, closing.
