### ISSUE TITLE
[Admin App] Add a new table with "types".

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/terms-service#38]
We need this feature to manage Terms in Admin App see https://github.com/topcoder-platform/admin-app/issues/153.

Currently, when we are editing/viwing **TermsOfUse** in Admin App we can only show `typeId` of **TermsOfUse**:

![image](https://user-images.githubusercontent.com/146016/93790152-61111180-fc3b-11ea-92e4-bd9b8be57067.png)

But in the old admin app, we could show textual values of `type` which is understandable by users:

![image](https://user-images.githubusercontent.com/146016/93790356-9cabdb80-fc3b-11ea-94bc-bf244f57ebc7.png)

In the Admin App we have to know all possible values of **types**: `id` + `title`:
1. Add a new table to Terms Service which would hold a table of types.
2. Add a new API endpoint to retrieve all the types with one call.

**Comment by rootelement** [comment]
Here's the data:
id | name
------------ | -------------
1 | High School Web Site Terms
2 | Corp Site Terms of Use
3 | Gneral Product Terms of Use
4 | Product Terms of Use
5 | Contest
6 | Reviewer Terms
7 | Testing Tool NDA
8 | Site Terms of Use
9 | Download Submission Terms of Use

**Comment by maxceem** [comment]
@rootelement @ThomasKranitsas 

This endpoint `GET https://api.topcoder-dev.com/v5/terms/type` returns error `500`:
```js
{
    "message": "Internal server error"
}
```

I'm calling it with the admin token like this:
```
curl --location --request GET 'https://api.topcoder-dev.com/v5/terms/type' \
--header 'Authorization: Bearer <ADMIN_TOKEN>'
```

**Comment by rootelement** [comment]
This is fixed in dev:
```
curl --location --request GET 'https://api.topcoder-dev.com/v5/terms/type' \
--header 'Authorization: Bearer <<JWT>>'
```

Response
```json
[
    {
        "id": 1,
        "name": "High School Web Site Terms"
    },
    {
        "id": 2,
        "name": "Corp Site Terms of Use"
    },
    {
        "id": 3,
        "name": "General Product Terms of Use"
    },
    {
        "id": 4,
        "name": "Product Terms of Use"
    },
    {
        "id": 5,
        "name": "Contest"
    },
    {
        "id": 6,
        "name": "Reviewer Terms"
    },
    {
        "id": 7,
        "name": "Testing Tool NDA"
    },
    {
        "id": 8,
        "name": "Site Terms of Use"
    },
    {
        "id": 9,
        "name": "Download Submission Terms of Use"
    }
]
```

**Comment by rootelement** [comment]
@maxceem i believe this is complete and can be closed, right?
