### ISSUE TITLE
[Admin App] Support filter TermsOfUse by "userId" who signed them

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/terms-service#39]
We need this feature to manage Terms in Admin App see https://github.com/topcoder-platform/admin-app/issues/153.

Terms Service has endpoint GET https://api.topcoder-dev.com/v5/terms which returns the list of **TermsOfUse**.

We need to support filtering **TermsOfUse** by `userId` who signed them. So the call like `GET https://api.topcoder-dev.com/v5/terms?userId=123456` would return records of **TermsOfUse** which are signed be user with specified `userId`.

**Comment by rootelement** [comment]
@maxceem i believe this is complete and can be closed, right?

**Comment by maxceem** [comment]
Yes, closing.
