### ISSUE TITLE
[Admin App] Endpoint to manage users who signed a particular Terms

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/terms-service#40]
We need this feature to manage Terms in Admin App see https://github.com/topcoder-platform/admin-app/issues/153.

### Overview

Admins should be able to list users who signed a particular Terms Of User. Additionally admins should be able to `sign` or `unsign` Terms for other users.
I suggest adding a new endpoint`/terms/:termsOfUseId/users` with `GET/POST/DELETE` commands.

### List - `GET /terms/:termsOfUseId/users`

This endpoint should return a list of users who signed Terms specified by `termsOfUseId`.

- As there might be a lot of users who signed one Terms, this endpoint should support pagination: `page` / `perPage` query params.
- Additionally, it might be good to have filters by:
   - `userId` - so we can quickly check if a particular user has signed the Terms. Also, it might be great, if we can support filtering by multiple users by providing a comma-separated list of users like `GET /terms/:termsOfUseId/users?userId=111111,222222,333333,444444`.
   - 2 query params `signedAtFrom` and `signedAtTo` to filter by the date when terms was signed. We can define one of these params or both of them. ([UserTermsOfUseXref](https://github.com/topcoder-platform/terms-service/blob/dev/src/models/UserTermsOfUseXref.js#L10) model has field `created` which could be used for this filter).

### Sign - `POST /terms/:termsOfUseId/users/`

- Should accept `body` in JSON format like:

   ```js
   {
     "userId": 123456 // the id of user who should sign the Terms
   }
   ```

### Unsign - `DELETE /terms/:termsOfUseId/users/:userId`

Should unsign the terms `termsOfUseId` for user specified by `userId`

**Comment by rootelement** [comment]
@maxceem I believe this is completed and can be closed right?

**Comment by maxceem** [comment]
Yes, closing.
